spring:
  application:
    name: gateway-zuul
server:
  port: 7755

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


#zuul:
#  routes:
#    eureka-client:
#      path: /hello/**
#      serviceId: eureka-client

#简化配置
zuul:
  routes:
    eureka-client: /hello/**
